main:
	gcc -O3 -Wall -ffast-math -o corr_cuba corr_cuba.c -I/home/schaich/lqcd/Cuba-4.2 -L/home/schaich/lqcd/Cuba-4.2 -lcuba -lm
	gcc -O3 -Wall -ffast-math -o corr_divonne corr_divonne.c -I/home/schaich/lqcd/Cuba-4.2 -L/home/schaich/lqcd/Cuba-4.2 -lcuba -lm
