#!/bin/bash

if [ $# -lt 1 ]; then
  echo "Usage: $0 <first>"
  exit 1
fi

# Input parameters
first=$1
if [ $# -gt 1 ]; then
  last=$2
else
  last=$1
fi

# Adjustable parameters
cpus=4
Ntraj=10
traj_length=1
skip=`echo $Ntraj | awk -v tau="$traj_length" '{print($1*tau)}'`
Nvec=12

# Parameters fixed by the path
temp=`pwd`
path=${temp##*APBC/Nc}  # Strip everything up to and including "APBC/Nc"
Ncvol=${path%%/*}       # Strip everything after and including "/"
Nt=${Ncvol##*nt}        # Strip everything up to and including "nt"
Nc=${Ncvol%%_*}         # Strip everything after and including "_"
tag=${path##*/l}        # Strip everything up to and including "/g"
#lambda=TODO...

echo "Hard-coding for Nc4_8nt8/l2.5_b0.44_G0.05..."
L=8
lambda=2.5
bmass=0.44
G=0.05
#echo "Hard-coding for Nc4_16nt32/l1.0_b0.28_G0.05..."
#L=16
#lambda=1.0
#bmass=0.28
#echo "Hard-coding for Nc3_16nt32/l1.5_b0.34_G0.05..."
#lambda=1.5
#bmass=0.34

# This will help check that things are set correctly
cd /home/schaich/SYM/APBC/Nc${Nc}_${L}nt$Nt/l${lambda}_b${bmass}_G$G
bin=/home/schaich/lqcd/susy/4d_Q16/bins/susy_eig-U$Nc

for(( i=$first ; $i<=$last ; i+=$skip )); do
  echo $i
  out=Out/eig.$i
  lat=Configs/gauge
  if [ -f $out ]; then
    echo "ERROR: OUTPUT FILE $out EXISTS, SUBMISSION ABORTED"
    rm -f temp
    exit 1
  fi
  if [ ! -f $lat.$i ]; then
    echo "ERROR: LATTICE $lat.$i NOT FOUND, SUBMISSION ABORTED"
    rm -f temp
    exit 1
  fi

  mpirun -np $cpus $bin << END >> $out
  prompt 0
  nx $L
  ny $L
  nz $L
  nt $Nt
  PBC -1

  iseed ${last}${g/\./41}${Nt}$i
  Nroot 1
  Norder 1

  warms 0
  trajecs $Ntraj
  traj_length $traj_length
  nstep 1
  nstep_gauge 1
  traj_between_meas $Ntraj

  lambda $lambda
  kappa_u1 0.0
  bmass $bmass
  fmass 0.0
  G $G

  max_cg_iterations 5000
  error_per_site 1e-5

  Nvec $Nvec
  eig_tol 1e-12
  maxIter 999999

  reload_serial $lat.$i
  forget
END
  chmod 664 $out $lat.$i*
done
