#!/bin/bash

if [ $# -lt 1 ]; then
  echo "Usage: $0 <first> [last (optional)]"
  exit 1
fi

# Input parameters
first=$1
if [ $# -gt 1 ]; then
  last=$2
else
  last=$1
fi

# Adjustable parameters
cpus=4
Nc=8
L=8
Nt=8
rt=6.5
ga=0.10
lambda=`echo $rt | awk -v nt="$Nt" '{print($1/nt)}'`
bmass=`echo $lambda | awk -v g="$ga" '{print($1 * g)}'`
cWline=`echo $lambda | awk -v g="$ga" '{print($1 * g)}'`
Ntraj=10
traj_length=1
skip=`echo $Ntraj | awk -v tau="$traj_length" '{print($1*tau)}'`
Nvec=12

# This will help check that things are set correctly
cd /home/schaich/SYM/3d/Nc${Nc}_${L}nt$Nt/rt${rt}_g$ga
bin=/home/schaich/dev/susy/4d_Q16/bins/susy_eig_dimred-U$Nc

for(( i=$first ; $i<=$last ; i+=$skip )); do
  echo $i
  out=Out/eig.$i
  lat=Configs/gauge.$i
  if [ -f $out ]; then
    echo "ERROR: OUTPUT FILE $out EXISTS, SUBMISSION ABORTED"
    rm -f temp
    exit 1
  fi
  if [ ! -f $lat ]; then
    echo "ERROR: LATTICE $lat NOT FOUND, SUBMISSION ABORTED"
    rm -f temp
    exit 1
  fi

  mpirun -np $cpus $bin << END >> $out
  prompt 0
  nx 1
  ny $L
  nz $L
  nt $Nt
  PBC -1

  iseed ${last}${lambda/\./41}${L}$i
  Nroot 1
  Norder 1
  warms 0
  trajecs $Ntraj
  traj_length $traj_length
  nstep 1
  nstep_gauge 1
  traj_between_meas $Ntraj

  lambda $lambda
  kappa_u1 0.0
  bmass $bmass
  fmass 0.0
  G 0.0
  cWline $cWline

  max_cg_iterations 5000
  error_per_site 1e-5

  Nvec $Nvec
  eig_tol 1e-10
  maxIter 99999

  reload_serial $lat
  forget
END
  chmod 664 $out $lat*
done
