#!/bin/bash

if [ $# -lt 5 ]; then
  echo "Usage: $0 <first> <last> nsteps:{<fermion> <gauge>} <time> [dependency (optional)]"
  exit 1
fi

# Input parameters
first=$1
last=$2
fsteps=$3
gsteps=$4
time=$5

# Adjustable parameters
cpus=8
Nt=16
g=0.01
f=0.12
mu=`echo | awk -v f="$f" -v nt="$Nt" '{print((1.0/(f*nt)))}'`
lambda=`echo | awk -v g="$g" -v mu="$mu" '{print(g*(mu**3))}'`
Ntraj=10
traj_length=1
skip=10   # !!! Should be a way to figure out skip=Ntraj*traj_length

# Common parameters for all jobs
tag=g${g}_f${f}_high
echo "#!/bin/sh" > temp
echo "#SBATCH -D ./" >> temp
echo "#SBATCH --export=ALL" >> temp
echo "#SBATCH -p nodes -n $cpus" >> temp
echo "#SBATCH -t $time" >> temp
echo "#SBATCH -J HMC12_nt${Nt}_$tag" >> temp
echo "#SBATCH -o hmc.%j.out" >> temp
echo "#SBATCH -e hmc.%j.out" >> temp
echo "#SBATCH --mem-per-cpu=1000M" >> temp
echo "#SBATCH --mail-user=david.schaich@liverpool.ac.uk" >> temp
echo "#SBATCH --mail-type=END,FAIL" >> temp
if [ $# -gt 5 ]; then
  echo "#SBATCH -d afterok:$6" >> temp
fi

# Should use dir due to SBATCH -D above, but let's make sure
dir=/mnt/lustre/users/schaich/SYM/BMN/Nc12_nt${Nt}_high/$tag
bin=/mnt/lustre/users/schaich/SYM/code/1d_Q16/bins/susy_hmc-N12
cd $dir
echo "cd $dir" >> temp

# Same modules as when compiling
echo "module load compilers/gcc/5.5.0" >> temp
echo "module load libs/gcc/5.5.0" >> temp
echo "module load mpi/openmpi/1.10.7/gcc-5.5.0" >> temp
echo "module load libs/blas/3.6.0/gcc-5.5.0" >> temp
echo "module load libs/lapack/3.5.0/gcc-5.5.0" >> temp

# Write all evolution tasks to run in a single job
iter=0
for(( i=$first ; $i<$last ; i+=$skip )); do
  iter=$[$iter + 1]
  next=$[$i + $skip]
  out=$dir/Out/out.$i-$next
  lat=$dir/Configs/gauge
  if [ -f $out ]; then
    echo "ERROR: OUTPUT FILE $out EXISTS, SUBMISSION ABORTED"
    rm -f temp
    exit 1
  fi
  echo "if [ ! -f $lat.$i ]; then" >> temp
  echo "  echo \"ERROR: LATTICE $lat.$i NOT FOUND, SUBMISSION ABORTED\"" >> temp
  echo "  exit 1" >> temp
  echo "fi" >> temp
  if [ -f $lat.$next ]; then
    echo "ERROR: LATTICE $lat.$next EXISTS, SUBMISSION ABORTED"
    rm -f temp
    exit 1
  fi

  echo "echo \"Job \$SLURM_JOB_NAME started \"\`date\`\" jobid \$SLURM_JOB_ID\" >> $out" >> temp
  echo "echo \"=== Running MPI application on $cpus cpus ===\" >> $out" >> temp
  echo "echo \"mpirun -quiet -np $cpus $bin\" >> $out" >> temp
  echo "mpirun -quiet -np $cpus $bin << EOF >> $out" >> temp
  echo "prompt 0" >> temp
  echo "nt $Nt" >> temp
  echo "PBC -1" >> temp
  echo "iseed ${last}${lambda/\./1}${Nt}$i" >> temp

  echo "Nroot 2" >> temp
  echo "Norder 15" >> temp

  echo "warms 0" >> temp
  echo "trajecs $Ntraj" >> temp
  echo "traj_length $traj_length" >> temp
  echo "nstep $fsteps" >> temp
  echo "nstep_gauge $gsteps" >> temp
  echo "traj_between_meas $Ntraj" >> temp

  echo "lambda $lambda" >> temp
  echo "mu $mu" >> temp

  echo "max_cg_iterations 5000" >> temp
  echo "error_per_site 1e-5" >> temp

  echo "reload_serial $lat.$i" >> temp
  echo "save_serial $lat.$next" >> temp
  echo "EOF" >> temp

  echo "echo \"=== MPI application finished at \"\`date\`\" ===\" >> $out" >> temp
  echo "chmod 664 $out $lat.$i* $lat.$next*" >> temp
  echo "" >> temp
done

sbatch temp
echo "Requested $time to run $iter jobs"
rm -f temp
