#!/bin/bash

if [ $# -lt 4 ]; then
  echo "Usage: $0 <first> <last> nsteps:{<fermion> <gauge>} [dependency (optional)]"
  exit 1
fi

# Input parameters
first=$1
last=$2
fsteps=$3
gsteps=$4

# Adjustable parameters
node=8
cpus=128
L=16
Nt=32
lambda=1.0
bmass=0.28
fmass=0.0
kappa=0.0
G=0.05
Ntraj=10
traj_length=1
skip=10   # !!! Should be a way to figure out skip=Ntraj*traj_length

# Common parameters for all jobs
tag=l${lambda}_b${bmass}_G$G
echo "#!/bin/bash" > temp
echo "#$ -N HMC4_${L}nt${Nt}_$tag" >> temp
echo "#$ -S /bin/bash" >> temp
echo "#$ -cwd" >> temp
echo "#$ -j y" >> temp
echo "#$ -pe orte $cpus" >> temp
echo "#$ -m ae -M schaich@itp.unibe.ch" >> temp

# For libmpi...
echo "export LD_LIBRARY_PATH=/usr/mpi/gcc/openmpi-1.6.5/lib:$LD_LIBRARY_PATH" >> temp

dir=/space4/schaich/SYM/APBC/Nc4_${L}nt${Nt}/$tag
bin=/space4/schaich/lqcd/susy/4d_Q16/bins/susy_hmc-U4
cd $dir
echo "cd $dir" >> temp

# Write all evolution tasks to run in a single job
iter=0
for(( i=$first ; $i<$last ; i+=$skip )); do
  iter=$[$iter + 1]
  next=$[$i + $skip]
  out=$dir/Out/out.$i-$next
  lat=$dir/Configs/gauge
  if [ -f $out ]; then
    echo "ERROR: OUTPUT FILE $out EXISTS, SUBMISSION ABORTED"
    rm -f temp
    exit 1
  fi
  echo "if [ ! -f $lat.$i ]; then" >> temp
  echo "  echo \"ERROR: LATTICE $lat.$i NOT FOUND, SUBMISSION ABORTED\"" >> temp
  echo "  exit 1" >> temp
  echo "fi" >> temp
  if [ -f $lat.$next ]; then
    echo "ERROR: LATTICE $lat.$next EXISTS, SUBMISSION ABORTED"
    rm -f temp
    exit 1
  fi

  echo "echo \"Job \$PBS_JOBNAME started \"\`date\`\" jobid \$PBS_JOBID\" >> $out" >> temp
  echo "echo \"=== Running MPI application on $cpus cpus ===\" >> $out" >> temp
  echo "echo \"mpirun -np $cpus $bin\" >> $out" >> temp
  echo "mpirun -np $cpus $bin << EOF >> $out" >> temp
  echo "prompt 0" >> temp
  echo "nx $L" >> temp
  echo "ny $L" >> temp
  echo "nz $L" >> temp
  echo "nt $Nt" >> temp
  echo "PBC -1" >> temp
  echo "iseed ${last}${lambda/\./41}${L}$i" >> temp

  echo "Nroot 1" >> temp
  echo "Norder 15" >> temp

  echo "warms 0" >> temp
  echo "trajecs $Ntraj" >> temp
  echo "traj_length $traj_length" >> temp
  echo "nstep $fsteps" >> temp
  echo "nstep_gauge $gsteps" >> temp
  echo "traj_between_meas $Ntraj" >> temp

  echo "lambda $lambda" >> temp
  echo "kappa_u1 $kappa" >> temp
  echo "bmass $bmass" >> temp
  echo "fmass $fmass" >> temp
  echo "G $G" >> temp

  echo "max_cg_iterations 5000" >> temp
  echo "error_per_site 1e-5" >> temp

  echo "reload_serial $lat.$i" >> temp
  echo "save_serial $lat.$next" >> temp
  echo "EOF" >> temp

  echo "echo \"=== MPI application finished at \"\`date\`\" ===\" >> $out" >> temp
  echo "chmod 664 $out $lat.$i* $lat.$next*" >> temp
  echo "" >> temp
done

if [ $# -gt 4 ]; then
  qsub -hold_jid $5 temp -r n
else
  qsub temp -r n
fi
echo "Requested to run $iter jobs"
rm -f temp
