#!/bin/bash

if [ $# -lt 5 ]; then
  echo "Usage: $0 <first> <last> nsteps:{<fermion> <gauge>} <time>"
  exit 1
fi

# Input parameters
first=$1
last=$2
fsteps=$3
gsteps=$4
time=$5

# Adjustable parameters
node=1
cpus=32
L=16
Nt=32
lambda=1.0
bmass=1.0
fmass=0.0
kappa=1.0
Ntraj=10
traj_length=1
skip=10   # !!! Should be a way to figure out skip=Ntraj*traj_length

# Common parameters for all jobs
tag=l${lambda}_b${bmass}_f${fmass}_k$kappa
echo "#!/bin/sh" > temp
echo "#PBS -l nodes=$node" >> temp
echo "#PBS -l walltime=$time" >> temp
echo "#PBS -A latticesusy" >> temp
echo "#PBS -q bc" >> temp
echo "#PBS -j oe" >> temp
echo "#PBS -N HMC${L}nt${Nt}_$tag" >> temp
echo "#PBS -o job.\$PBS_JOBID.out" >> temp
echo "#PBS -k oe" >> temp
echo "#PBS -m ae -M daschaich@gmail.com" >> temp

dir=/lqcdproj/latticesusy/N4/APBC/Nc2_${L}nt${Nt}/$tag
bin=/lqcdproj/latticesusy/N4/code/susy_hmc-bc
cd $dir
echo "cd $dir" >> temp

# Write all evolution tasks to run in a single job
iter=0
for(( i=$first ; $i<$last ; i+=$skip )); do
  iter=$[$iter + 1]
  next=$[$i + $skip]
  out=$dir/Out/out.$i-$next
  lat=$dir/Configs/gauge
  if [ -f $out ]; then
    echo "ERROR: OUTPUT FILE $out EXISTS, SUBMISSION ABORTED"
    rm -f temp
    exit 1
  fi
  echo "if [ ! -f $lat.$i ]; then" >> temp
  echo "  echo \"ERROR: LATTICE $lat.$i NOT FOUND, SUBMISSION ABORTED\"" >> temp
  echo "  exit 1" >> temp
  echo "fi" >> temp
  if [ -f $lat.$next ]; then
    echo "ERROR: LATTICE $lat.$next EXISTS, SUBMISSION ABORTED"
    rm -f temp
    exit 1
  fi

  echo "echo \"Job \$PBS_JOBNAME started \"\`date\`\" jobid \$PBS_JOBID\" >> $out" >> temp
  echo "echo \"=== Running MPI application on $cpus cpus ===\" >> $out" >> temp
  echo "echo \"/usr/local/mvapich/bin/mpirun -np $cpus $bin\" >> $out" >> temp
  echo "/usr/local/mvapich/bin/mpirun -np $cpus $bin << EOF  >> $out" >> temp
  echo "prompt 0" >> temp
  echo "nx $L" >> temp
  echo "ny $L" >> temp
  echo "nz $L" >> temp
  echo "nt $Nt" >> temp
  echo "iseed ${last}41$i" >> temp

  echo "warms 0" >> temp
  echo "trajecs $Ntraj" >> temp
  echo "traj_length $traj_length" >> temp
  echo "nstep $fsteps" >> temp
  echo "nstep_gauge $gsteps" >> temp
  echo "traj_between_meas $Ntraj" >> temp
  echo "lambda $lambda" >> temp
  echo "kappa_u1 $kappa" >> temp
  echo "bmass $bmass" >> temp
  echo "fmass $fmass" >> temp

  echo "max_cg_iterations 5000" >> temp
  echo "error_per_site 1e-5"
  echo "error_per_site 1e-5" >> temp
  echo "nsrc 3" >> temp
  echo "reload_serial $lat.$i" >> temp
#  echo "fresh" >> temp
  echo "no_gauge_fix" >> temp
  echo "save_serial $lat.$next" >> temp
  echo "EOF" >> temp

  echo "echo \"=== MPI application finished at \"\`date\`\" ===\" >> $out" >> temp
  echo "chmod 664 $out $lat.$i* $lat.$next*" >> temp
  echo "" >> temp
done

qsub temp
echo "Requested $time to run $iter jobs"
rm -f temp
