#!/bin/bash
if [ $# == 1 ]; then
  cd $1
fi

if [ `ls -1 Out/rescaled_eig.* | wc -l` -gt 0 ] ; then
  echo "Rescaled:"
  grep "EIGENVALUE 0 " Out/rescaled_eig.* | awk '{print $3}' | sort -g | head -n 1
  grep "BIGEIGVAL  0 " Out/rescaled_eig.* | awk '{print $3}' | sort -gr | head -n 1
  echo "Original:"
fi
grep "EIGENVALUE 0 " Out/eig.* | awk '{print $3}' | sort -g | head -n 1
grep "BIGEIGVAL  0 " Out/eig.* | awk '{print $3}' | sort -gr | head -n 1
