#!/bin/bash
# ------------------------------------------------------------------
if [ $# != 0 ]; then
  echo "Usage: $0"
  exit 1
fi

temp=`pwd`
dir=${temp##*SYM/}   # Strip everything up to and including "SYM/"
inpath=/raidc/users/schaich/SYM/$dir        # Customized for Liverpool
outpath=/raide/www/people/staff/schaich/SYM/$dir
# ------------------------------------------------------------------



# ------------------------------------------------------------------
# Construct list of files in given ensemble, for parse_BMN.py
rm -f list.txt
for i in $inpath/Out/out.* ; do
  echo ${i##*.} >> temp    # Strip everything up to and including the last "."
done
sort temp -n | uniq > list.txt
rm -f temp

# Use list of files in given ensemble to extract time series data
rm -f $outpath/data/*.csv $outpath/ERRORS
echo "python2 ~schaich/scripts/parse_BMN.py"
python2 ~schaich/scripts/parse_BMN.py
chmod 644 $outpath/data/*.csv
rm -f list.txt            # Done with this

# It looks like the lowest BMN eigenvalues should be reliable
# so long as they're at least doubled, which this script will check
# This script checks more than pairing, but pairing is all we care about here
python2 ~schaich/scripts/check_eig_pairs.py | grep pairing >> $outpath/ERRORS

# Replace Web page to update timestamp
date=`date`
rm -f $outpath/index.html
echo writeBMN $dir "$date"
~schaich/scripts/writeBMN $dir "$date"
chmod 644 $outpath/index.html

# I like to monitor this (looks better without $outpath)
#grep Apparent ERRORS
wc -l M*
wc -l E*
echo
# ------------------------------------------------------------------
