#!/bin/bash
# ------------------------------------------------------------------
if [ $# != 0 ]; then
  echo "Usage: $0"
  exit 1
fi

temp=`pwd`
dir=${temp##*SYM/}   # Strip everything up to and including "SYM/"
path=/nfs/beowulf03/schaich/SYM/$dir
# ------------------------------------------------------------------



# ------------------------------------------------------------------
# Construct list of files in given ensemble, for parse_SYM.py
rm -f list.txt
for i in $path/Out/out.* ; do
  echo ${i##*.} >> temp    # Strip everything up to and including the last "."
done
sort temp -n | uniq > list.txt
rm -f temp

# Use list of files in given ensemble to extract time series data
rm -f data/*.csv ERRORS
date=`date`
echo "python ~schaich/scripts/parse_SYM.py"
python ~schaich/scripts/parse_SYM.py
chmod 664 data/*.csv
rm -f list.txt            # Done with this

# Check eigenvalue measurements
python ~schaich/scripts/check_eig_pairs.py

# Replace Web page to update timestamp
date=`date`
rm -f index.html
echo writeSYM $dir "$date"
~schaich/scripts/writeSYM $dir "$date"
chmod 664 index.html

# I like to monitor this
wc -l M*
wc -l E*
echo
# ------------------------------------------------------------------
