#!/bin/bash
# ------------------------------------------------------------------
if [ $# != 0 ]; then
  echo "Usage: $0"
  exit 1
fi

temp=`pwd`
dir=${temp##*BMN/}   # Strip everything up to and including "BMN/"
path=/nfs/beowulf03/schaich/SYM/BMN/$dir      # Customized for CU
# ------------------------------------------------------------------



# ------------------------------------------------------------------
# Construct list of files in given ensemble, for parse_BMN.py
rm -f list.txt
for i in $path/Out/out.* ; do
  echo ${i##*.} >> temp    # Strip everything up to and including the last "."
done
sort temp -n | uniq > list.txt
rm -f temp

# Use list of files in given ensemble to extract time series data
rm -f data/*.csv ERRORS
echo "python ~schaich/scripts/parse_BMN.py"
python ~schaich/scripts/parse_BMN.py
chmod 664 data/*.csv
rm -f list.txt            # Done with this

# Not yet sure what structure BMN eigenvalues should have
#python ~schaich/scripts/check_eig_pairs.py >> ERRORS

# Replace Web page to update timestamp
date=`date`
rm -f index.html
echo writeBMN $dir "$date"
~schaich/scripts/writeBMN $dir "$date"
chmod 664 index.html

# I like to monitor this
#grep Apparent ERRORS
wc -l M*
wc -l E*
echo
# ------------------------------------------------------------------
