#!/bin/bash
# ------------------------------------------------------------------
if [ $# != 0 ]; then
  echo "Usage: $0"
  exit 1
fi

temp=`pwd`
dir=${temp##*SYM/}   # Strip everything up to and including "SYM/"
inpath=/raidc/users/schaich/SYM/$dir        # Customized for Liverpool
outpath=/raid1/backup/schaich/SYM/$dir
# ------------------------------------------------------------------



# ------------------------------------------------------------------
# Construct list of files in given ensemble, for parse_SYM.py
rm -f list.txt
for i in $inpath/Out/out.* ; do
  echo ${i##*.} >> temp    # Strip everything up to and including the last "."
done
sort temp -n | uniq > list.txt
rm -f temp

# Use list of files in given ensemble to extract time series data
rm -f $outpath/data/*.csv $outpath/ERRORS
echo "python ~schaich/scripts/parse_SYM.py"
python ~schaich/scripts/parse_SYM.py
chmod 664 $outpath/data/*.csv
rm -f list.txt            # Done with this

# Check eigenvalue measurements
python ~schaich/scripts/check_eig_pairs.py >> $outpath/ERRORS

# Replace Web page to update timestamp
date=`date`
rm -f $outpath/index.html
echo writeSYM $dir "$date"
~schaich/scripts/writeSYM $dir "$date"
chmod 664 $outpath/index.html

# I like to monitor this (looks better without $outpath)
grep Apparent ERRORS
wc -l M*
wc -l E*
echo
# ------------------------------------------------------------------
