#!/bin/bash

if [ ! -d /raid1/backup/schaich/SYM/3d ] ; then
  echo "Error: /raid1 doesn't seem to be mounted"
  exit 1
fi

cd ~/SYM/3d
#for i in N*/rt* ; do
for i in N*/l* ; do
  if [ -d /raid1/backup/schaich/SYM/3d/$i/data ] ; then
    echo "$i already done"
    continue
  fi

  echo "Doing $i"
  mkdir /raid1/backup/schaich/SYM/3d/$i
  mkdir /raid1/backup/schaich/SYM/3d/$i/data
  touch /raid1/backup/schaich/SYM/3d/$i/ERRORS
  touch /raid1/backup/schaich/SYM/3d/$i/MISSING

  cd $i
  rm -f data ERRORS MISSING
  ln -s /raid1/backup/schaich/SYM/3d/$i/data
  ln -s /raid1/backup/schaich/SYM/3d/$i/ERRORS
  ln -s /raid1/backup/schaich/SYM/3d/$i/MISSING
  ls -l
  cd ../..
done
