#!/bin/bash

if [ ! -d /raide/www/people/staff/schaich/SYM/bosonicBMN ] ; then
  echo "Error: /raide doesn't seem to be mounted"
  exit 1
fi

cd ~/SYM/bosonicBMN
for i in N*/g* ; do
  if [ -d /raide/www/people/staff/schaich/SYM/bosonicBMN/$i/data ] ; then
    echo "$i already done"
    continue
  fi

  echo "Doing $i"
  mkdir /raide/www/people/staff/schaich/SYM/bosonicBMN/$i
  mkdir /raide/www/people/staff/schaich/SYM/bosonicBMN/$i/data
  touch /raide/www/people/staff/schaich/SYM/bosonicBMN/$i/ERRORS
  touch /raide/www/people/staff/schaich/SYM/bosonicBMN/$i/MISSING

  cd $i
  rm ERRORS MISSING
  rm -f data ERRORS MISSING
  ln -s /raide/www/people/staff/schaich/SYM/bosonicBMN/$i/data
  ln -s /raide/www/people/staff/schaich/SYM/bosonicBMN/$i/ERRORS
  ln -s /raide/www/people/staff/schaich/SYM/bosonicBMN/$i/MISSING
  ls -l
  cd ../..
done
