#!/bin/bash

if [ ! -d /raide/www/people/staff/schaich/SYM/3d ] ; then
  echo "Need to mount /raide..."
  sudo mount sune.amtp:/raide /raide
fi

cd ~/SYM/3d
for i in N*/rt* ; do
#for i in N*/l* ; do
  if [ -d /raide/www/people/staff/schaich/SYM/3d/$i/data ] ; then
    echo "$i already done"
    continue
  fi

  echo "Doing $i"
  mkdir /raide/www/people/staff/schaich/SYM/3d/$i
  mkdir /raide/www/people/staff/schaich/SYM/3d/$i/data
  touch /raide/www/people/staff/schaich/SYM/3d/$i/ERRORS
  touch /raide/www/people/staff/schaich/SYM/3d/$i/MISSING

  cd $i
  rm -f data ERRORS MISSING
  ln -s /raide/www/people/staff/schaich/SYM/3d/$i/data
  ln -s /raide/www/people/staff/schaich/SYM/3d/$i/ERRORS
  ln -s /raide/www/people/staff/schaich/SYM/3d/$i/MISSING
  ls -l
  cd ../..
done
