#!/bin/bash

if [ ! -d /raide/www/people/staff/schaich/SYM/2d_Q4 ] ; then
  echo "Error: /raide doesn't seem to be mounted"
  exit 1
fi

cd ~/SYM/2d_Q4
for i in N*/rt* ; do
  if [ -d /raide/www/people/staff/schaich/SYM/2d_Q4/$i/data ] ; then
    echo "$i already done"
    continue
  fi

  echo "Doing $i"
  mkdir /raide/www/people/staff/schaich/SYM/2d_Q4/$i
  mkdir /raide/www/people/staff/schaich/SYM/2d_Q4/$i/data
  touch /raide/www/people/staff/schaich/SYM/2d_Q4/$i/ERRORS
  touch /raide/www/people/staff/schaich/SYM/2d_Q4/$i/MISSING

  cd $i
  rm -f data ERRORS MISSING
  ln -s /raide/www/people/staff/schaich/SYM/2d_Q4/$i/data
  ln -s /raide/www/people/staff/schaich/SYM/2d_Q4/$i/ERRORS
  ln -s /raide/www/people/staff/schaich/SYM/2d_Q4/$i/MISSING
  ls -l
  cd ../..
done
